### PR TITLE
Chatフロント

### PR DESCRIPTION
**Pull request by nobutanita**
フロント実装いたしました。

### CODE REVIEW

**Comment by nobutanita** [comment]
元データgemfileです。
ーーーーーーーーーーーーーーーーーーーーー
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.7', '>= 5.0.7.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.6.0'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'font-awesome-sass'

**Comment by nobutanita** [comment]
元データmessages.scssです。
ーーーーーーーーーーーーーーーーーーーーー
.wrapper {
  @include flexbox;
}

**Comment by nobutanita** [comment]
元データmessages/intex.html.hamlです。

 ーーーーーーーーーーーーーーーーーーーーー 
.wrapper

  = render 'shared/side_bar'

  .chat
    .header
      .left-header
        .left-header__title
        %ul.left-header__members
          Member：
          %li.member
          %li.member
          
      .right-header
        .right-header__button
          Edit
    .messages
      .message
        .upper-message
          .upper-message__user-name
          .upper-message__date
        .lower-meesage
          .lower-message__content
      .message
        .upper-message
          .upper-message__user-name
          .upper-message__date
        .lower-meesage
          .lower-message__content
          
    .form
      %form
        %input.form__message
        .form__mask
          %label.form__mask__image
            = icon('fa','image',class: 'icon')
            %input.hidden{type: 'file'}
        %input.form__submit{type: 'submit', value: 'Send'}

**Comment by shingoteshima** [comment]
Files changedで差分がすべて見れるようにしましょう。

**Comment by nobutanita** [comment]
Files changedのサイトは下記を確認してください
https://github.com/nobutanita/chat-space/pull/11/files

**Pull request merged**
